serverIP   = "143.106.243.64"
serverPort = "3306"
database   = "CashFlow2026"
driver     = "jdbc:mariadb"
tail       = "?useUnicode=true" + "&characterEncoding=utf8" + "&connectionCollation=utf8mb4_unicode_ci";

